# Generated by Django 3.2 on 2022-01-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotrans', '0002_auto_20220118_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_amount',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
