# Generated by Django 3.2 on 2022-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotrans', '0003_withdraw_amount_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_amount',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
