# Generated by Django 3.2 on 2022-01-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotrans', '0004_alter_withdraw_amount_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw_amount',
            old_name='update',
            new_name='withdraw_date',
        ),
        migrations.RemoveField(
            model_name='curr_account',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='saving_account',
            name='update_at',
        ),
    ]
