# Generated by Django 3.2 on 2022-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotrans', '0005_auto_20220119_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curr_account',
            name='acc_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curr_account',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saving_account',
            name='acc_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saving_account',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdraw_amount',
            name='acc_no',
            field=models.IntegerField(),
        ),
    ]
